# Generated by Django 5.2 on 2025-04-15 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Denuncia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assunto', models.CharField(max_length=150)),
                ('mensagem', models.TextField(max_length=1500)),
                ('chave_acesso', models.CharField(editable=False, max_length=10, unique=True)),
                ('encerrada', models.BooleanField(default=False)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
